name: mason
description: >
  A Dart template generator which helps teams generate files quickly and consistently.
version: 0.0.1-dev.15
homepage: https://github.com/felangel/mason

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.6.0
  checked_yaml: ^1.0.2
  http: ^0.12.2
  io: ^0.3.4
  json_annotation: ^3.0.1
  mustache_template: ^1.0.0+1
  path: ^1.7.0
  recase: ^3.0.1
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  build_version: ^2.0.1
  json_serializable: ^3.3.0
  test: ^1.14.3

executables:
  mason:
