name: mason_logger
description: A reusable Dart logger used by the Mason CLI (package:mason_cli).
version: 0.3.0
homepage: https://github.com/felangel/mason
repository: https://github.com/felangel/mason
issue_tracker: https://github.com/felangel/mason/issues
documentation: https://github.com/felangel/mason/tree/master/packages/mason_logger#readme
topics: [cli, logger, mason]
funding: [https://github.com/sponsors/felangel]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
  io: ^1.0.4
  win32: ^5.5.4

dev_dependencies:
  meta: ^1.15.0
  mocktail: ^1.0.4
  test: ^1.25.8
