name: mason_cli
description: >
  Mason CLI allows developers to create and consume reusable templates called bricks.
version: 0.1.3
homepage: https://github.com/felangel/mason
repository: https://github.com/felangel/mason
issue_tracker: https://github.com/felangel/mason/issues
documentation: https://docs.brickhub.dev
topics: [mason, cli, template, generator]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.5.0
  checked_yaml: ^2.0.3
  cli_completion: ^0.5.1
  mason: ^0.1.0
  mason_api: ^0.1.0
  meta: ^1.15.0
  path: ^1.9.0
  pub_updater: ^0.5.0
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  collection: ^1.19.0
  mocktail: ^1.0.4
  test: ^1.25.8

executables:
  mason:
