name: mason_cli
description: >
  A Dart template generator which helps teams generate files quickly and consistently.
version: 0.1.0-dev.1
homepage: https://github.com/felangel/mason

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason: ^0.0.1-dev.57
  mason_logger: ^0.1.0-dev.2
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  build_version: ^2.0.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

dependency_overrides:
  mason:
    path: ../mason

executables:
  mason:
