name: mason
description: >
  A Dart template generator which helps teams generate files quickly and consistently.
version: 0.1.0-dev.51
homepage: https://github.com/felangel/mason
repository: https://github.com/felangel/mason
issue_tracker: https://github.com/felangel/mason/issues
documentation: https://github.com/felangel/mason/tree/master/packages/mason_cli#readme
topics: [mason, template, generator]

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  archive: ^3.1.11
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  convert: ^3.1.0
  crypto: ^3.0.1
  http: '>=0.13.3 <2.0.0'
  json_annotation: ^4.8.1
  mason_logger: ^0.2.9
  meta: ^1.7.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.1
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^1.0.0
  test: ^1.17.0
