name: mason
description: >
  A Dart template generator which helps teams generate files quickly and consistently.
version: 0.1.0-dev.39
homepage: https://github.com/felangel/mason
repository: https://github.com/felangel/mason
issue_tracker: https://github.com/felangel/mason/issues
documentation: https://github.com/felangel/mason/tree/master/packages/mason_cli#readme

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  archive: ^3.1.11
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  convert: ^3.1.0
  crypto: ^3.0.1
  http: ^0.13.3
  json_annotation: ^4.4.0
  mason_logger: ^0.2.2
  meta: ^1.7.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.1
  pub_semver: ^2.1.0
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^2.4.0
