name: mason
description: >
  A Dart template generator which helps teams generate files quickly and consistently.
version: 0.1.2
homepage: https://github.com/felangel/mason
repository: https://github.com/felangel/mason
issue_tracker: https://github.com/felangel/mason/issues
documentation: https://docs.brickhub.dev
topics: [mason, template, generator]
funding: [https://github.com/sponsors/felangel]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  archive: ^4.0.0
  checked_yaml: ^2.0.3
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.5
  http: ^1.2.2
  json_annotation: ^4.9.0
  mason_logger: ^0.3.0
  meta: ^1.15.0
  mustache_template: ^2.0.0
  path: ^1.9.0
  pool: ^1.5.1
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ">=6.8.0 <6.10.0"
  mocktail: ^1.0.4
  test: ^1.25.8
