name: pub_score

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  verify_pub_score:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.5.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana

      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning)
          SCORE=$(echo $PANA | sed -n "s/Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          IFS='/'
          read -a SCORE_ARR <<< "$SCORE"
          echo "SCORE: ${SCORE_ARR[0]}"
          echo "TOTAL: ${SCORE_ARR[1]}"
